repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
#   - repo: https://github.com/mark-gutenberger/betterls
#     # rev: v0.1.0
#     hooks:
#       - id: trunk.io
#       - id: clang-format
